# Generated by Django 4.1.4 on 2023-01-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart3', '0002_cart_created_date_cart_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='count',
            new_name='quantity',
        ),
    ]
