# Generated by Django 4.1.3 on 2022-12-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(default='some random address', max_length=150),
        ),
        migrations.AlterField(
            model_name='shop',
            name='business_time',
            field=models.CharField(default='From 10am to 12', max_length=150),
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_time',
            field=models.CharField(default='Between 15 to 20', max_length=70),
        ),
        migrations.AlterField(
            model_name='shop',
            name='mobile',
            field=models.CharField(default='18519204393', max_length=11),
        ),
    ]
