# Generated by Django 4.1.3 on 2022-12-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts0', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
