# Generated by Django 4.1.3 on 2022-12-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='backend/products2/images/products/carrots.jpg', upload_to='products2/images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='My product', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, default=650.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('L', 'Litre'), ('bottle', 'Bottle'), ('glass', 'Glass'), ('1 pc', 'Piece')], default='L', max_length=10),
        ),
    ]
