# Generated by Django 4.1.4 on 2023-01-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0003_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
