# Generated by Django 4.1.4 on 2023-01-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
