// User Auth dispatch states
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const RESEND_ACTIVATION_SUCCESS = 'RESEND_ACTIVATION_SUCCESS';
export const RESEND_ACTIVATION_FAIL = 'RESEND_ACTIVATION_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
// user info
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';

export const EMAIL_RESET_SUCCESS = 'EMAIL_RESET_SUCCESS'
export const EMAIL_RESET_FAIL = 'EMAIL_RESET_FAIL'
export const EMAIL_RESET_CONFIRM_SUCCESS = 'EMAIL_RESET_CONFIRM_SUCCESS'
export const EMAIL_RESET_CONFIRM_FAIL = 'EMAIL_RESET_CONFIRM_FAIL'

// Social auth section
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_FAIL = 'REFRESH_FAIL'

// loading/spinner
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

// User Profile
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

// Alerts dispatch states
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Delete User
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
// show loading
export const SET_CATEGORIES_LOADING = 'SET_CATEGORIES_LOADING';
export const REMOVE_CATEGORIES_LOADING = 'REMOVE_CATEGORIES_LOADING';

// Shops
export const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS'
export const GET_SHOPS_FAIL = 'GET_SHOPS_FAIL';

// loading for shops
export const SET_SHOPS_LOADING = 'SET_SHOPS_LOADING';
export const REMOVE_SHOPS_LOADING = 'REMOVE_SHOPS_LOADING';


// Products
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
// show loading
export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const REMOVE_PRODUCTS_LOADING = 'REMOVE_PRODUCTS_LOADING';

