# Generated by Django 4.1.4 on 2022-12-24 14:15

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0002_order_uuid_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', unique=True),
        ),
    ]
