# Generated by Django 4.1.4 on 2022-12-24 14:19

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0003_order_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=11, max_length=11, prefix='', unique=True),
        ),
    ]
