# Generated by Django 4.1.4 on 2022-12-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0004_alter_order_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
    ]
