# Generated by Django 4.1.4 on 2022-12-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0007_deliveryaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
