# Generated by Django 4.1.4 on 2022-12-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0012_deliveryaddress_status_alter_deliveryaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders5.deliveryaddress'),
        ),
    ]
