# Generated by Django 4.1.4 on 2022-12-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0014_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='status',
            new_name='addr_status',
        ),
    ]
