# Generated by Django 4.1.4 on 2023-01-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0015_rename_status_deliveryaddress_addr_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
