# Generated by Django 4.1.4 on 2023-01-01 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_address4', '0002_rename_full_name_deliveryaddress_name'),
        ('orders5', '0016_remove_order_address_delete_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_address4.deliveryaddress'),
        ),
    ]
