# Generated by Django 4.1.4 on 2023-01-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0017_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
