# Generated by Django 4.1.4 on 2023-01-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0018_alter_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='count',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
