# Generated by Django 4.1.4 on 2023-01-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0019_remove_orderitem_count_remove_orderitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=1, default=40, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=1, default=40.4, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=1, default=33, max_digits=7),
            preserve_default=False,
        ),
    ]
