# Generated by Django 4.1.4 on 2023-01-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0020_order_delivery_fee_order_service_fee_order_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
