# Generated by Django 4.1.4 on 2023-01-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0021_rename_amount_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
    ]
