# Generated by Django 4.1.4 on 2023-01-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders5', '0022_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='some product name', max_length=64),
            preserve_default=False,
        ),
    ]
