# Generated by Django 4.1.4 on 2023-01-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_address4', '0002_rename_full_name_deliveryaddress_name'),
        ('orders5', '0023_orderitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery_address4.deliveryaddress'),
            preserve_default=False,
        ),
    ]
